pub-key von Nutzer entfernt
ADFC-Hamburg/adfc-ansible pull request #209
Opened 2022-02-08 13:02 UTC by zyxtaxbo

in nächster Zeit keine aktive Rolle im Projekt

2022-02-08 16:46 UTC, tabacha commented
Hallo Mathias, dass ist schön dass du daran denkst dich zu disablen, wenn du nicht am Projekt teilnehmen möchtest. Der Richtige weg ist aber dich aus  der entsprechenden Variable auszutragen, weil nur so auch dein Key auf den Rechnern gelöscht wird,

Siehe: https://github.com/ADFC-Hamburg/adfc-ansible/pull/210

2022-02-08 16:47 UTC, tabacha requested changes
So, wird der Key nur im Ansible entfernt aber nicht auf den Rechnern wo er liegt.

2022-02-08 16:48 UTC, tabacha commented
Wenn du einverstanden bist, würde ich diesen Pull-Request schießen und den 210 er Mergen.

2022-02-09 10:56 UTC, zyxtaxbo commented
ja, kannst Du machen.

2022-02-10 16:56 UTC, closed without merging